before_script:
  - whoami
  - docker info
variables:
  IMAGE_NAME: "box/nginx"
build:
  script:
    - docker build -t $IMAGE_NAME .
push-image-to-registry:
  script:
    - docker tag $IMAGE_NAME registry.cn-hangzhou.aliyuncs.com/boxfish/nginx:latest
    - docker login --username=**** --password=***** registry.cn-hangzhou.aliyuncs.com
    - docker push registry.cn-hangzhou.aliyuncs.com/boxfish/nginx:latest
deploydocker:
  script:
    - ./deploy.sh
